# Generated by Django 2.2.5 on 2019-09-22 16:51

from django.db import migrations, models
import shrt.url.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=2000)),
                ('tag', models.CharField(default=shrt.url.models.generate_tag, max_length=4)),
                ('shortened', models.CharField(max_length=255)),
            ],
        ),
    ]
