# Generated by Django 2.2.5 on 2019-09-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=255)),
                ('shortened', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=4, unique=True)),
            ],
        ),
    ]
